[workspace]
resolver = "2"
members = ["src-tauri"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "Proprietary"
rust-version = "1.80"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "warn"
dbg_macro = "deny"
